google_api_key = ''
firebase_api_key = 'AIzaSyARCliKyACLYhK_1qlK8a3IUSvQ4Do_3Jc'
firebase_service_account = 'firebase-adminsdk-mrcka@uhs-devils-advocate.iam.gserviceaccount.com'
google_client_id = ''
google_client_secret = ''
gmail_password = 'killerskill!'
google_app_password = ''